name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        uses: mhdehghanzadeh/action-build-pbf-glyphs@v1
        with:
          source: fonts/
          target: build/fonts/
